name: CI

on:
  push:
    branches:
      - 'main'
      - 'github-action-branch'
  

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Docker-compose
        run: docker-compose up --build -d

      - name: Checking Containers
        run: docker ps 

      - name: Checking test results
        run: docker logs pyforge-python-school-3-test-1 | grep "8 passed" || exit 1
        






 