name: CI

on:
  push:
    branches:
      - 'main'
      - 'postgres-branch'
      - 'test-branch'
      - 'logging'
  
jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Docker-compose
        run: docker-compose up --build -d
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          MAIN_DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}


      - name: Checking Containers
        run: docker ps 

      - name: Wait for container to stabilize
        run: sleep 5

      - name: Run tests and capture logs
        run: |
              docker logs pyforge-python-school-3_web1 
              docker logs pyforge-python-school-3_web2
              (docker logs pyforge-python-school-3_web1 | grep "9 passed" || docker logs pyforge-python-school-3_web2 | grep "9 passed") || exit 1

  flake8:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
            python-version: 3.11.9
            architecture: x64

      - name: Checkout PyTorch
        uses: actions/checkout@master

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
