name: CI

on:
  push:
    branches:
      - 'main'
      - 'github-action-branch'
  

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker-compose
        run: docker-compose up --build -d

      - name: Checking Containers
        run: docker ps 

      - name: Checking test results
        run: docker logs test | grep "8 success" || exit 1






 